tests:
	@echo "=================== Running wave_dirichlet test ==================="
	cd test_mms_wave_dirichlet; make
	@echo "=================== Running strong wave_dirichlet test ==================="
	cd test_mms_wave_strong_dirichlet; make
	@echo "=================== Running wave_flather test ==================="
	cd test_mms_wave_flather; make
	@echo "=================== Running wave_flather advection test ==================="
	cd test_mms_wave_advection_flather; make
	@echo "=================== Running wave_flather friction test ==================="
	cd test_mms_wave_friction_flather; make
	@echo "=================== Running wave_flather diffusion test ==================="
	cd test_mms_wave_diffusion_flather; make
	@echo "=================== Running test_partial_derivative_turbine test ==================="
	cd test_partial_derivative_turbine; make
	@echo "=================== Running friction gradient test ==================="
	cd test_gradient_friction; make
	@echo "=================== Running position gradient test with strong boundary conditions ==================="
	cd test_gradient_pos_strong_dirichlet; make
	@echo "=================== Running optimal friction mini model test ==================="
	cd test_optimal_friction_mini_model; make
	@echo "=================== Running optimal position mini model test ==================="
	cd test_optimal_position_mini_model; make
	@echo "=================== Running optimal friction for single turbine test ==================="
	cd test_optimal_friction_single_turbine; make
	@echo "=================== Running constraint derivatives test ==================="
	cd test_constraint_derivatives; make
	@echo "=================== All tests passed ===================" 
