.PHONY: mesh 

mesh:	
	cd mesh; make mesh
	@echo "*************************************************************"
	@echo "Now go to one of the subdirectories to start the optimisation"
	@echo "*************************************************************"

clean_mesh:
	rm -f *.xml
	rm -f *.xml.bak
	rm -f *.msh

