""" Problems for OpenTidalFarm """

from problem import Problem
from steady_shallow_water import SteadyShallowWaterProblemParameters
from steady_shallow_water import SteadyShallowWaterProblem
from multi_steady_shallow_water import MultiSteadyShallowWaterProblemParameters
from multi_steady_shallow_water import MultiSteadyShallowWaterProblem
from shallow_water import ShallowWaterProblemParameters
from shallow_water import ShallowWaterProblem
from dummy import DummyProblemParameters
from dummy import DummyProblem
